# Site settings
title: TzeSing的博客
email: jjzzxx000@outlook.com
qqemail: 850971066@qq.com
description: > # this means to ignore newlines until "baseurl:"
  记录每天的心情和收获，不积跬步无以至千里！
copyright: >
  本站所有内容的版权归作者所有，如需转载和使用请与作者联系，
  请尊重知识，尊重版权。
#baseurl: "/~zuoyuan/blog" # the subpath of your site, e.g. /blog/
#url: "http://home.ustc.edu.cn" # the base hostname & protocol for your site
zhihu_username: TzeSing
github_username:  TzeSing

# Build settings
markdown: kramdown


# wiki
#wikiurl: /wiki
zhihuurl: "https://www.zhihu.com/people/TzeSing/"
githuburl: "https://github.com/TzeSing/TzeSing.github.io"